# Nombre de tu aplicación
spring.application.name=parquimetro

# Conexión a la base de datos en Laragon
spring.datasource.url=jdbc:mysql://localhost:3306/estacionamiento_iesnh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# CONFIGURACIÓN DE MERCADO PAGO Y NGROK
# ==========================================

mercadopago.access.token=APP_USR-3245725303743029-070309-4dd3117213f7aa2bf9ba4aa67f843c13-3324744578
# URL del Frontend (React) para redirigir al usuario cuando termine de pagar
app.frontend.url=http://localhost:5173

# 🚀 URL PÚBLICA DEL BACKEND (Ngrok)
# Aquí debes pegar el link que te da Ngrok al ejecutar 'ngrok http 8080'. 
# Mercado Pago usará esto para avisar en segundo plano que el pago fue exitoso (Webhooks).
app.backend.url=https://bulk-hurler-flashbulb.ngrok-free.dev