# Nombre de la aplicación
spring.application.name=parquimetro

# ==========================================
# CONEXIÓN A BASE DE DATOS
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://parkinh-parkinhdb-nfcbmd:3306/estacionamiento_iesnh?useSSL=false&serverTimezone=America/Argentina/Jujuy&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# MERCADO PAGO Y RUTAS DE LA APLICACIÓN
# ==========================================

# Token de acceso de Mercado Pago (Producción / Pruebas)
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:APP_USR-COLOCAR-TOKEN-EN-DOCKPLOY}

# URL pública del Frontend en React
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

# URL pública del Backend (API Spring Boot en Contabo)
app.backend.url=${APP_BACKEND_URL:http://localhost:8080}